Touch improvements, Logging mask
inputlabs/alpakka_firmware pull request #132
Opened 2024-08-21 14:53 UTC by marcos-diaz

2024-08-22 12:55 UTC, przymi requested changes

2024-08-22 12:55 UTC, przymi commented on src/logging.c
> +bool logging_get_mask() {
Returns enum, not bool

2024-08-22 12:55 UTC, przymi commented on src/headers/touch.h
> -#define CFG_TOUCH_SMOOTH 2  // Ticks.
Smoothing is removed? Should be in notes.

2024-08-22 12:55 UTC, przymi commented on src/headers/touch.h
> +// The starting baseline threshold value when using dynamic.
dynamic => auto

2024-09-24 12:48 UTC, marcos-diaz commented on src/headers/touch.h
> -#define CFG_TOUCH_SMOOTH 2  // Ticks.
Redefined as `CFG_TOUCH_AUTO_SMOOTH`

2024-09-27 19:38 UTC, merged