Fixed home button double-press issue, Fixed home profile latching actions issue
inputlabs/alpakka_firmware pull request #138
Opened 2024-09-24 11:26 UTC by marcos-diaz

#126 and #136

2024-09-24 11:28 UTC, marcos-diaz commented on src/profile.c
> +// Check if profile has been requested to be reset (usually after profile change).
Git does a poor job here, this is a new function extracted away from the function below

2024-09-25 07:11 UTC, przymi commented on src/hid.c
> +int8_t state_matrix[256] = {0,};
Add comment that negative means an error condition

2024-09-25 07:11 UTC, przymi commented on src/headers/hid.h
> +void hid_matrix_reset(uint8_t exclude);
Where do I find some documentation on this hid_matrix?

2024-09-26 09:06 UTC, przymi requested changes

2024-09-26 09:06 UTC, przymi commented on src/hid.c
> +(output) and internal operations (procedures). It keep track of how many
Actions are coming from the user. What are internal operations in this context?

2024-09-26 09:06 UTC, przymi commented on src/hid.c
> +references to these actions are active. As a simplification: Button presses
How many references (to prior actions?) are kept and where?

2024-09-26 09:06 UTC, przymi commented on src/hid.c
> +The state matrix is a representation of all the actions that could be sent
So this is the HID matrix.

2024-09-26 09:06 UTC, przymi commented on src/hid.c
> +void hid_matrix_reset(uint8_t keep) {
What is "keep"?
According to the description above, "state matrix is usually re-initialized (reset) to zeros when the user changes the active profile"

2024-09-26 09:06 UTC, przymi commented on src/hid.c
> +        if (state_matrix[key] > 0) {  // Do not allow to wrap / go negative.
What is the difference between keys and actions in the index of state_matrix?
Would not all of these have been reset above?

2024-09-26 09:06 UTC, przymi commented on src/hid.c
> +            else if (key >= MOUSE_INDEX) synced_mouse = false;
These two are already false after line 66

2024-09-26 09:06 UTC, przymi commented on src/profile.c
> +void profile_check_reset() {
THis is not checking if there is / or should be a reset, but it is executing a reset

2024-09-26 09:06 UTC, przymi commented on src/profile.c
> +        hid_matrix_reset(pending_reset_keep);
???

2024-09-26 09:06 UTC, przymi commented on src/profile.c
> +void profile_report_active() {
What is this supposed to do?

2024-09-26 09:06 UTC, przymi commented on src/profile.c
> +        home_is_active = false;  // Force normal home profile off.
Is this the home profile? I.e. only active while the home button is pressed?

2024-09-27 19:47 UTC, marcos-diaz commented on src/hid.c
> +void hid_matrix_reset(uint8_t keep) {
The high level documentation cannot explain all the implementation corner cases, I will add more code comments instead.

2024-09-27 19:49 UTC, marcos-diaz commented on src/hid.c
> +        if (state_matrix[key] > 0) {  // Do not allow to wrap / go negative.
That's legacy naming from when the only actions were keys (in the context of key presses and releases). 

Fixing the terminology would require renaming a lot of variables and function names across the whole project. Out of the scope of this PR.

2024-09-27 19:51 UTC, marcos-diaz commented on src/hid.c
> +            else if (key >= MOUSE_INDEX) synced_mouse = false;
There are different functions with different triggers and usecases

2024-09-27 20:33 UTC, marcos-diaz commented on src/profile.c
> +        home_is_active = false;  // Force normal home profile off.
Actually the line was not needed, was removed

2024-09-27 20:35 UTC, merged