Multigenerational touch values, Remake of the dynamic threshold algo
inputlabs/alpakka_firmware pull request #41
Opened 2023-05-22 11:42 UTC by marcos-diaz

Also the tune values are not "threshold" values anymore, but "sensitivity" values (from less sensitive to most sensitive) for consistency with the other tune settings

2023-05-22 14:46 UTC, marcos-diaz commented on src/touch.c
> +    if (elapsed == 0) elapsed = threshold / CFG_TOUCH_DYNAMIC_PEAK_RATIO;
This could be improved.

2023-05-25 12:35 UTC, przymi requested changes

2023-05-25 12:35 UTC, przymi commented on src/headers/touch.h
> +#define CFG_GEN0_TOUCH_TIMEOUT 20  // Microseconds.
Please provide either documentation or link to documentation as to which PCB versions belong to GEN0 and to GEN1

2023-05-25 12:35 UTC, przymi commented on src/headers/touch.h
> +#define CFG_GEN0_TOUCH_DYNAMIC_MIN 3  // Microseconds
What were these for? Please comment on the impact of these constants

2023-05-25 12:35 UTC, przymi commented on src/touch.c
> +uint8_t threshold_from_config = 0;
This should now be sensitivity_config

2023-05-25 12:35 UTC, przymi commented on src/touch.c
> +        if (!(x % 40)) printf("%i %.2f\n", elapsed, threshold);
What is this magic number 40?

2023-05-25 14:50 UTC, merged