Added rotary test, Disable and restore current profile while testing
inputlabs/alpakka_firmware pull request #43
Opened 2023-05-24 15:02 UTC by marcos-diaz

2023-05-24 15:34 UTC, tomas-pecserke requested changes

2023-05-24 15:34 UTC, tomas-pecserke commented on src/headers/profile.h
> +extern uint8_t profile_active_index;
This breaks encapsulation principle - it bad practice to expose implementation variable (and for write access no less).

There already is `void profile_set_active(uint8_t)` function, let's add a get function to go with it.

2023-05-24 15:34 UTC, tomas-pecserke commented on src/headers/rotary.h
> +extern int8_t rotary_increment;
Same here. Let's not expose implementation details like this if headers.

2023-05-24 15:34 UTC, tomas-pecserke commented on src/self_test.c
> +    rotary_increment = 0;
this could use `rotaty.reset()` instead

2023-05-24 17:08 UTC, marcos-diaz commented on src/headers/profile.h
> +extern uint8_t profile_active_index;
True I will make some set/get funcs

2023-05-24 20:11 UTC, tomas-pecserke commented
A note on commit message format:

1) It's better to split functionality into separate commits for better readability of commit history.
1) It's preferable to use present tense in commit messages for better readability of commit history.

This way you read what each commit does, not what the developer did. Focus is on the commit itself.

Therefore

- `Disable profile before testing and restore afterwards`
- `Add rotary test`

reads much better than

- `Added rotary test, Disable and restore current profile while testing`

2023-05-25 11:20 UTC, tomas-pecserke approved these changes

2023-05-25 12:11 UTC, merged