Racing profile
inputlabs/alpakka_firmware pull request #52
Opened 2023-08-07 12:26 UTC by marcos-diaz

2023-08-24 13:16 UTC, przymi commented on src/hid.c
> +    gamepad_lx += value;
Just a comment: for all these cases, this is now reporting the absolute value, no longer relative to previous.

2023-08-24 13:16 UTC, przymi commented on src/hid.c
> +    if (procedure == PROC_ROTARY_MODE_0) rotary_set_mode(0);
What are these modes?

2023-08-24 13:16 UTC, przymi commented on src/headers/vector.h
> +    float r;
might want to add comment that this is in radiants

2023-08-24 13:16 UTC, przymi commented on src/headers/button.h
> +    NORMAL,
Should already have been there: some explanation as to what those modes are.
Especially for new hold_overlap_ and _long

2023-08-24 13:16 UTC, przymi commented on src/headers/button.h
>      void (*handle_hold_double_press) (Button *self);
Missing hold_overlap and hold_overlap_long

2023-08-24 13:16 UTC, przymi commented on src/headers/config.h
> +#define CFG_IMU_CALIBRATION_SAMPLES 200000
4-fold increase due to improved budget in 1.5.1 SDK?

2023-08-24 13:16 UTC, przymi commented on src/headers/config.h
> +#define CFG_ACCEL_CORRECTION_SMOOTH 50
Magic numbers. What is the effect of this constant? What do the values / changes imply?

2023-08-24 13:16 UTC, przymi commented on src/headers/gyro.h
> +    double absolute_x_min;
missing z for flight profile.

2023-08-24 13:16 UTC, przymi commented on src/headers/gyro.h
> +    uint8_t actions_x_neg[4];
Would be good to comment that up to four modifiers can be provided

2023-08-24 13:16 UTC, przymi commented on src/headers/gyro.h
> -void gyro_report();
why were these removed?

2023-08-24 13:16 UTC, przymi commented on src/headers/helper.h
> +#define is_between(value, low, high)  ( (value >= low) && (value <= high) )
is_betweeen_or_equal
But is this really necessary?

2023-08-24 13:16 UTC, przymi commented on src/headers/helper.h
> +#define ramp_low(x, z)  ( x<z ? 0 : (x-z) * (1 / (1-z)) )
Needs explanations!

2023-08-24 13:16 UTC, przymi commented on src/headers/imu.h
> -typedef struct vector {
moved to vector.h

2023-08-24 13:16 UTC, przymi commented on src/headers/imu.h
> -#define IMU_CTRL2_G_125 0b10100010
Where are these now?

2023-08-24 13:16 UTC, przymi commented on src/headers/imu.h
> +#define IMU_CTRL1_XL 0x10
Some explanation please

2023-08-24 13:16 UTC, przymi commented on src/headers/rotary.h
> +    uint8_t actions[8][2][4];
Documentation needed

2023-08-24 13:16 UTC, przymi commented on src/headers/tusb_config.h
> +#define TUD_HID_REPORT_DESC_GAMEPAD_CUSTOM(...) \
Link to documentation

2023-08-24 13:16 UTC, przymi commented on src/headers/tusb_config.h
> +typedef struct TU_ATTR_PACKED {
Ditto

2023-08-24 13:16 UTC, przymi commented on src/headers/vector.h
> +Vector vector_negative(Vector v);
invert

2023-08-24 13:16 UTC, przymi commented on src/hid.c
> +    int32_t buttons = (
Documentation?

2023-08-24 13:16 UTC, przymi commented on src/hid.c
> +    int16_t lx_report = hid_axis(gamepad_lx, GAMEPAD_AXIS_LX, GAMEPAD_AXIS_LX_NEG) * BIT_15;
???

2023-08-25 09:39 UTC, przymi requested changes

2023-08-25 09:39 UTC, przymi commented on src/hid.c
> +            else if (!synced_mouse && (priority_mouse > priority_gamepad)) {
Why only in the else? It would appear that these reports should always be sent / synced. So no else, and the fall-through seems correct.

2023-08-25 09:39 UTC, przymi commented on src/hid.c
> +        hid_gamepad_reset();
Why a reset after the report(s) is sent?

2023-08-25 09:39 UTC, przymi commented on src/imu.c
> +    uint8_t xl = bus_spi_read_one(cs, IMU_CTRL1_XL);
So Ctrl is now xl and g is new. But what does this do?

2023-08-25 09:39 UTC, przymi commented on src/imu.c
> +        (double)-z - offset_z,
Why inverted?

2023-08-25 09:39 UTC, przymi commented on src/imu.c
>          if (!(i % 5000)) led_cycle_step();
What is this magic?

2023-08-25 09:39 UTC, przymi commented on src/imu.c
> +    while(i < CFG_IMU_CALIBRATION_SAMPLES) {
Previously this was some magic 200000

2023-08-25 09:39 UTC, przymi commented on src/imu.c
> +    if (mode==1) *z += BIT_14;  // Newton's fault for inventing the gravity.
???

2023-08-25 09:39 UTC, przymi commented on src/main.c
> +            // if (!(i % 50)) printf("%i", tick_idle);
???

2023-08-25 09:39 UTC, przymi commented on src/profiles/console.c
> +    printf("  Console: ");
Why changes in the console profile? Separate PR?

2023-08-25 09:39 UTC, przymi commented on src/profiles/console_legacy.c
> +    printf("  Console legacy: ");
Ditto

2023-08-25 09:39 UTC, przymi commented on src/profiles/desktop.c
> +    printf("  Desktop: ");
Ditto

2023-08-25 09:39 UTC, przymi commented on src/rotary.c
> +void rotary_set_mode(uint8_t value) {
SOem documentation would be nice.

2023-08-25 09:39 UTC, przymi commented on src/thumbstick.c
> -    if      (axis == GAMEPAD_AXIS_LX)     hid_gamepad_lx( value * ANALOG_FACTOR);
What happened to the factor?

2023-08-25 09:39 UTC, przymi commented on src/thumbstick.c
> -    if      (axis == GAMEPAD_AXIS_LX)     hid_gamepad_lx( value * ANALOG_FACTOR);
This requires some documentation

2023-08-25 09:39 UTC, przymi commented on src/thumbstick.c
> +    if (is_between(angle, -b, -a)) mask += DIR4_LEFT;
(0), 1, 2, 4, 8

2023-08-25 09:39 UTC, przymi commented on src/thumbstick.c
> +        if (direction & DIR4_LEFT)  self->left.virtual_press = true;
???

2023-08-25 09:39 UTC, przymi commented on src/vector.c
> +Vector vector_negative(Vector v) {
better to name "invert" or something

2023-08-25 09:39 UTC, przymi commented on src/vector.c
> +    return  (Vector){
Check that 0 < factor < 1

2023-08-25 09:39 UTC, przymi commented on src/vector.c
> +    float theta = rotation / 2;
Why /2?

2023-08-25 09:39 UTC, przymi commented on src/vector.c
> +Vector4 quaternion(Vector vector, float rotation) {
rotation in degress

2023-08-25 09:39 UTC, przymi commented on src/vector.c
> +        cos(theta)
rotation in rad?

2023-08-25 09:39 UTC, przymi commented on src/vector.c
> +Vector4 qmultiply(Vector4 q1, Vector4 q2) {
https://en.wikipedia.org/wiki/Quaternion

2023-08-30 08:43 UTC, marcos-diaz commented on src/hid.c
> +    gamepad_lx += value;
This is so multiple physical axis can be combined into a single virtual one, I will comment on the code.

2023-08-30 08:49 UTC, marcos-diaz commented on src/headers/button.h
> +    NORMAL,
Added link to dev manual reference (too much to explain in-code)

2023-08-30 08:50 UTC, marcos-diaz commented on src/headers/button.h
>      void (*handle_hold_double_press) (Button *self);
It is handled by the same method with a time parameter

2023-08-30 08:51 UTC, marcos-diaz commented on src/headers/config.h
> +#define CFG_IMU_CALIBRATION_SAMPLES 200000
It was never used but hardcoded elsewhere, I will make a comment anyways

2023-08-30 09:38 UTC, marcos-diaz commented on src/headers/gyro.h
> +    double absolute_x_min;
Flight profile would possibly use only X and Y, but in any case that will be added later if needed.

2023-08-30 09:39 UTC, marcos-diaz commented on src/headers/gyro.h
> -void gyro_report();
These are methods in the gyro class now.

2023-08-30 10:25 UTC, marcos-diaz commented on src/headers/imu.h
> -#define IMU_CTRL2_G_125 0b10100010
Same file, sorted differently

2023-08-30 10:51 UTC, marcos-diaz commented on src/hid.c
> +            else if (!synced_mouse && (priority_mouse > priority_gamepad)) {
They are not always sent, so the USB communication is more lean. Will comment on it.

2023-08-30 11:02 UTC, marcos-diaz commented on src/imu.c
> +    uint8_t xl = bus_spi_read_one(cs, IMU_CTRL1_XL);
This is only for printing it in the logs.

2023-08-30 11:08 UTC, marcos-diaz commented on src/vector.c
> +    return  (Vector){
the acceptable range would be anything `>0`. but then what to do if it is not?

2023-08-30 11:12 UTC, marcos-diaz commented on src/thumbstick.c
> -    if      (axis == GAMEPAD_AXIS_LX)     hid_gamepad_lx( value * ANALOG_FACTOR);
These are now in the [-1,1] range all the way until before being sent.

2023-08-30 11:14 UTC, marcos-diaz commented on src/thumbstick.c
> +    if (is_between(angle, -b, -a)) mask += DIR4_LEFT;
described in enum

2023-08-30 11:21 UTC, marcos-diaz commented on src/vector.c
> +    float theta = rotation / 2;
Linked wikipedia

2023-08-30 12:56 UTC, marcos-diaz commented on src/main.c
> +            // if (!(i % 50)) printf("%i", tick_idle);
This will be clean up in another PR reworking the logging + webusb

2023-08-31 12:42 UTC, merged