Mouse 16bit
inputlabs/alpakka_firmware pull request #93
Opened 2023-12-29 07:58 UTC by marcos-diaz

#87

2023-12-29 12:43 UTC, przymi requested changes

2023-12-29 12:43 UTC, przymi commented on src/headers/tusb_config.h
> +        HID_REPORT_SIZE ( 16                                     ) ,\
Comment that this is the important difference?

2023-12-29 12:43 UTC, przymi commented on src/hid.c
> +    uint8_t scroll = state_matrix[MOUSE_SCROLL_UP] - state_matrix[MOUSE_SCROLL_DOWN];
What happens with out of bounds values?

2024-01-15 15:54 UTC, marcos-diaz commented on src/hid.c
> +    uint8_t scroll = state_matrix[MOUSE_SCROLL_UP] - state_matrix[MOUSE_SCROLL_DOWN];
User cannot realistically scroll up or down 256 times in 4 milliseconds (1 polling cycle).

2024-01-15 16:07 UTC, merged